# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
gem "inflection", "1.0.0"
  gem "multipart-post", "2.2.3", require_name: "net/http/post/multipart"
  gem "faraday-multipart", "1.0.4", require_name: "faraday/multipart"
  gem "zendesk_api", "1.38.0.rc1"
